//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RO_Crate_validator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoCrateMetadataExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoCrateMetadataExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RO_Crate_validator.RoCrateMetadataExamples", typeof(RoCrateMetadataExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@context&quot;:&quot;https://w3id.org/ro/crate/0.2-DRAFT/context&quot;,&quot;@graph&quot;:[{&quot;@id&quot;:&quot;ro-crate-metadata.jsonld&quot;,&quot;about&quot;:{&quot;@id&quot;:&quot;.&quot;},&quot;additionalType&quot;:{&quot;@id&quot;:&quot;https://w3id.org/ro/crate/0.2-DRAFT/&quot;},&quot;creator&quot;:{&quot;@id&quot;:&quot;https://orcid.org/0000-0001-9842-9718&quot;}},{&quot;@type&quot;:[&quot;Dataset&quot;],&quot;@id&quot;:&quot;.&quot;,&quot;path&quot;:&quot;./&quot;,&quot;name&quot;:&quot;RetroPath2.0 IBISBA workflow node&quot;,&quot;datePublished&quot;:&quot;2019-02-14&quot;,&quot;contactPoint&quot;:{&quot;@id&quot;:&quot;#contact&quot;},&quot;creator&quot;:[{&quot;@id&quot;:&quot;#thomas&quot;},{&quot;@id&quot;:&quot;#stefan&quot;}],&quot;license&quot;:{&quot;@id&quot;:&quot;http://creativecommons.org/licenses/by-nc-sa/4.0/&quot;}, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoCrateExample1 {
            get {
                return ResourceManager.GetString("RoCrateExample1", resourceCulture);
            }
        }
    }
}
